apiVersion: v1
kind: Service
metadata:
  name: bluegreen-active
spec:
  type: NodePort   # ✅ expose via NodePort
  selector:
    app: bluegreen-demo
  ports:
  - protocol: TCP
    port: 80          # Service Port
    targetPort: 80    # Container Port
    nodePort: 30083   # Fixed NodePort (optional, else auto-assigned)

